/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import controlador.DriverEnfermera;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Santa Gutierrez
 */
public class VentanaConsultaEnfermera extends javax.swing.JFrame {

    private VentanaAdministrador ventAdmin;
    private DriverEnfermera contEnfermera;
    /**
     * Creates new form VentanaConsultarEnfermera
     */
    public VentanaConsultaEnfermera() {
        initComponents();
        contEnfermera = new DriverEnfermera();
        
    jEmail.setVisible(false);
    jLApellido_dos.setVisible(false);
    jLApellido_uno.setVisible(false);
    jLArea.setVisible(false);
    jLCargo.setVisible(false);
    jLDireccion.setVisible(false);
    jLAnios.setVisible(false);
    jLJefe.setVisible(false);
    jLNombres.setVisible(false);
    jLSalario.setVisible(false);
    jTApellido_dos.setVisible(false);
    jTApellido_uno.setVisible(false);
    jTArea.setVisible(false);
    jTCargo.setVisible(false);
    jTDireccion.setVisible(false);
    jTAnios.setVisible(false);
    jTJefe.setVisible(false);
    jTNombres.setVisible(false);
    jTSalario.setVisible(false);
    jTemail.setVisible(false);
    

    jTApellido_dos.setEditable(false);
    jTApellido_uno.setEditable(false);
    jTArea.setEditable(false);
    jTCargo.setEditable(false);
    jTDireccion.setEditable(false);
    jTAnios.setEditable(false);
    jTJefe.setEditable(false);
    jTNombres.setEditable(false);
    jTSalario.setEditable(false);
    jTemail.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTIdentificacion = new javax.swing.JTextField();
        jLIdentificacion = new javax.swing.JLabel();
        jLNombres = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTNombres = new javax.swing.JTextField();
        jLApellido_uno = new javax.swing.JLabel();
        jTApellido_uno = new javax.swing.JTextField();
        jLApellido_dos = new javax.swing.JLabel();
        jTApellido_dos = new javax.swing.JTextField();
        jLDireccion = new javax.swing.JLabel();
        jTDireccion = new javax.swing.JTextField();
        jLArea = new javax.swing.JLabel();
        jTArea = new javax.swing.JTextField();
        jLSalario = new javax.swing.JLabel();
        jTSalario = new javax.swing.JTextField();
        jEmail = new javax.swing.JLabel();
        jTemail = new javax.swing.JTextField();
        jLCargo = new javax.swing.JLabel();
        jTCargo = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jLJefe = new javax.swing.JLabel();
        jTJefe = new javax.swing.JTextField();
        jBAtras = new javax.swing.JButton();
        jLAnios = new javax.swing.JLabel();
        jTAnios = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLIdentificacion.setText("Identificacion: ");

        jLNombres.setText("Nombres:");

        jLabel1.setText("Consultar Medico");

        jLApellido_uno.setText("Primer Apellido:");

        jLApellido_dos.setText("Segundo Apellido:");

        jLDireccion.setText("Dirección:");

        jLArea.setText("Codigo área:");

        jLSalario.setText("Salario:");

        jEmail.setText("E-mail:");

        jLCargo.setText("Cargo:");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLJefe.setText("Jefe:");

        jBAtras.setText("Atras");
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });

        jLAnios.setText("Años Experiencia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(jLAnios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLIdentificacion)
                        .addComponent(jLNombres)
                        .addComponent(jLApellido_uno)
                        .addComponent(jLApellido_dos)
                        .addComponent(jLDireccion)
                        .addComponent(jLArea)
                        .addComponent(jLSalario)
                        .addComponent(jEmail)
                        .addComponent(jLCargo))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(0, 124, Short.MAX_VALUE))
                        .addComponent(jTNombres, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTApellido_dos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTArea, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTSalario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTemail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTCargo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTApellido_uno)
                        .addComponent(jTIdentificacion, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBBuscar)
                            .addGap(23, 23, 23)
                            .addComponent(jLJefe)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTJefe, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addComponent(jBAtras))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAnios)
                    .addComponent(jTAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(276, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLIdentificacion)
                                .addComponent(jTIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLJefe)
                                .addComponent(jTJefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jBBuscar))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLNombres)
                        .addComponent(jTNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLApellido_uno)
                        .addComponent(jTApellido_uno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLApellido_dos)
                        .addComponent(jTApellido_dos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLDireccion)
                        .addComponent(jTDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLArea)
                        .addComponent(jTArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLSalario)
                        .addComponent(jTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jEmail)
                        .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLCargo)
                                .addComponent(jTCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBAtras)
                            .addGap(4, 4, 4)))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        String identificacion = jTIdentificacion.getText();

        if(identificacion.equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese la identificación");
        }else{
            ArrayList<String> enfermera = new ArrayList();
            if(contEnfermera.estaEnfermera(identificacion)){
                enfermera = contEnfermera.consultarEnfermera(identificacion);

                jTIdentificacion.setEditable(false);
                jEmail.setVisible(true);
                jLApellido_dos.setVisible(true);
                jLApellido_uno.setVisible(true);
                jLArea.setVisible(true);
                jLCargo.setVisible(true);
                jLDireccion.setVisible(true);
                jLAnios.setVisible(true);
                jLJefe.setVisible(true);
                jLNombres.setVisible(true);
                jLSalario.setVisible(true);
                jTApellido_dos.setVisible(true);
                jTApellido_uno.setVisible(true);
                jTArea.setVisible(true);
                jTCargo.setVisible(true);
                jTDireccion.setVisible(true);
                jTAnios.setVisible(true);
                jTJefe.setVisible(true);
                jTNombres.setVisible(true);
                jTSalario.setVisible(true);
                jTemail.setVisible(true);

                jTApellido_dos.setText(enfermera.get(2));
                jTApellido_uno.setText(enfermera.get(1));
                jTArea.setText(enfermera.get(4));
                jTCargo.setText(enfermera.get(7));
                jTDireccion.setText(enfermera.get(3));
                jTAnios.setText(enfermera.get(9));
                jTJefe.setText(enfermera.get(8));
                jTNombres.setText(enfermera.get(0));
                jTSalario.setText(enfermera.get(5));;
                jTemail.setText(enfermera.get(6));
            }else{
                JOptionPane.showMessageDialog(null, "La identificación no pertenece al personal Enfermera del sistema");
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        // TODO add your handling code here:
        ventAdmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBAtrasActionPerformed

    public void acomodarVentana(VentanaAdministrador ventAdmin){
    
        this.ventAdmin = ventAdmin;
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaEnfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaEnfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaEnfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaEnfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaEnfermera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jLAnios;
    private javax.swing.JLabel jLApellido_dos;
    private javax.swing.JLabel jLApellido_uno;
    private javax.swing.JLabel jLArea;
    private javax.swing.JLabel jLCargo;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLIdentificacion;
    private javax.swing.JLabel jLJefe;
    private javax.swing.JLabel jLNombres;
    private javax.swing.JLabel jLSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTAnios;
    private javax.swing.JTextField jTApellido_dos;
    private javax.swing.JTextField jTApellido_uno;
    private javax.swing.JTextField jTArea;
    private javax.swing.JTextField jTCargo;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTIdentificacion;
    private javax.swing.JTextField jTJefe;
    private javax.swing.JTextField jTNombres;
    private javax.swing.JTextField jTSalario;
    private javax.swing.JTextField jTemail;
    // End of variables declaration//GEN-END:variables
}
