/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import logica.Persona;
import controlador.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.*;
import logica.Telefono;
import excepciones.*;

/**
 *
 * @author juliancv
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    private VentanaLogin ventLog;
    private Persona sesion;
    private Validador validar = new Validador();
    private DriverArea area;
    
    private ArrayList <Telefono> telefonos = new ArrayList<>();
    
    /**
     * Creates new form VentanaAdministrador
     */
    public VentanaAdministrador() {
        initComponents();
        area = new DriverArea();
    }
    
    
    public void datosUsuario (Persona usuario) {
        
        sesion = usuario;
        lbUser.setText("@" + sesion.getNombre());
        
    }
    
    public void registrarArea () {
        
        String codigo = campoCodigoArea.getText();
        String nombre = campoNombreArea.getText();
        String descripcion = areaDescripArea.getText();
        boolean estado = true;
        area.registrarArea(codigo, nombre, descripcion, estado);
        JOptionPane.showMessageDialog(this, "Se ha registrado el área correctamente",
                "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lbEstadoCama = new javax.swing.JLabel();
        lbCodAreaCama = new javax.swing.JLabel();
        lbNumCama = new javax.swing.JLabel();
        lbDescripCama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaDescripCama = new javax.swing.JTextArea();
        comboAreasCama = new javax.swing.JComboBox();
        comboEstadocama = new javax.swing.JComboBox();
        btAgregarCama = new javax.swing.JButton();
        campoNumeroCama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbNombreMedicamento = new javax.swing.JLabel();
        lbCodigoMedicamento = new javax.swing.JLabel();
        lbCostoMedicamento = new javax.swing.JLabel();
        lbDescripMedicamento = new javax.swing.JLabel();
        campoNomMedicamento = new javax.swing.JTextField();
        campoCodigoMedicamento = new javax.swing.JTextField();
        campoCostoMedicamento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaDescripMedicamento = new javax.swing.JTextArea();
        btAgregarMedicamento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbSubTituloArea = new javax.swing.JLabel();
        lbNombreArea = new javax.swing.JLabel();
        lbCodigoArea = new javax.swing.JLabel();
        lbDescripArea = new javax.swing.JLabel();
        campoNombreArea = new javax.swing.JTextField();
        campoCodigoArea = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaDescripArea = new javax.swing.JTextArea();
        btAgregarArea = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btListaEmpleados = new javax.swing.JButton();
        btCuentasEmpleados = new javax.swing.JButton();
        lbListaEmpleados = new javax.swing.JLabel();
        lbCuentasEmpleados = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbNombreUsu = new javax.swing.JLabel();
        lbPApellidoUsu = new javax.swing.JLabel();
        lbSApellidoUsu = new javax.swing.JLabel();
        lbTipoIdenUsu = new javax.swing.JLabel();
        lbNumIdenUsu = new javax.swing.JLabel();
        lbTelUsu = new javax.swing.JLabel();
        lbDirUsu = new javax.swing.JLabel();
        LbTipoUsu = new javax.swing.JLabel();
        campoNomUsu = new javax.swing.JTextField();
        campoSApellido = new javax.swing.JTextField();
        campoPApellido = new javax.swing.JTextField();
        comboTipoIdent = new javax.swing.JComboBox();
        campoNumIdenUsu = new javax.swing.JTextField();
        campoDirUsu = new javax.swing.JTextField();
        combotipoUsu = new javax.swing.JComboBox();
        btAgregarUsu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        registrarTelefono = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();
        btCerrarSesion = new javax.swing.JButton();
        lbBienvenido = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));

        lbEstadoCama.setText("Estado");

        lbCodAreaCama.setText("Codigo de Area");

        lbNumCama.setText("Numero ");

        lbDescripCama.setText("Descripcion");

        AreaDescripCama.setColumns(20);
        AreaDescripCama.setRows(5);
        jScrollPane1.setViewportView(AreaDescripCama);

        comboAreasCama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Area1" }));

        comboEstadocama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libre", "Ocupada" }));

        btAgregarCama.setText("Agregar");

        jLabel1.setText("Nueva Cama");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAgregarCama, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNumCama)
                            .addComponent(lbEstadoCama)
                            .addComponent(lbCodAreaCama)
                            .addComponent(lbDescripCama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(comboEstadocama, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoNumeroCama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboAreasCama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(184, 184, 184))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumeroCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumCama))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbEstadoCama)
                        .addGap(30, 30, 30)
                        .addComponent(lbCodAreaCama))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboEstadocama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboAreasCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescripCama))
                .addGap(65, 65, 65)
                .addComponent(btAgregarCama)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Administracion de camas", jPanel3);

        jPanel5.setBackground(new java.awt.Color(254, 254, 254));

        lbNombreMedicamento.setText("Nombre");

        lbCodigoMedicamento.setText("Codigo");

        lbCostoMedicamento.setText("Costo");

        lbDescripMedicamento.setText("Descripcion");

        AreaDescripMedicamento.setColumns(20);
        AreaDescripMedicamento.setRows(5);
        jScrollPane2.setViewportView(AreaDescripMedicamento);

        btAgregarMedicamento.setText("Agregar");

        jLabel3.setText("Nuevo Medicamento");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAgregarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombreMedicamento)
                                    .addComponent(lbCodigoMedicamento)
                                    .addComponent(lbCostoMedicamento)
                                    .addComponent(lbDescripMedicamento))
                                .addGap(106, 106, 106)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoCostoMedicamento)
                                    .addComponent(campoNomMedicamento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCodigoMedicamento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel3)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreMedicamento)
                    .addComponent(campoNomMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoMedicamento)
                    .addComponent(campoCodigoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCostoMedicamento)
                    .addComponent(campoCostoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripMedicamento)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btAgregarMedicamento)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Medicamentos", jPanel4);

        jPanel6.setBackground(new java.awt.Color(254, 254, 254));

        lbSubTituloArea.setText(" Nueva Area");

        lbNombreArea.setText("Nombre");

        lbCodigoArea.setText("Codigo");

        lbDescripArea.setText("Descripcion");

        areaDescripArea.setColumns(20);
        areaDescripArea.setLineWrap(true);
        areaDescripArea.setRows(5);
        areaDescripArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(areaDescripArea);

        btAgregarArea.setText("Agregar");
        btAgregarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(lbSubTituloArea))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(lbNombreArea)
                            .addGap(143, 143, 143)
                            .addComponent(campoNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbCodigoArea)
                                .addComponent(lbDescripArea))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoCodigoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btAgregarArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSubTituloArea)
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreArea)
                    .addComponent(campoNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoArea)
                    .addComponent(campoCodigoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripArea)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAgregarArea)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Areas", jPanel6);

        jPanel7.setBackground(new java.awt.Color(254, 254, 254));

        btListaEmpleados.setBorderPainted(false);
        btListaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btListaEmpleadosMouseClicked(evt);
            }
        });

        btCuentasEmpleados.setBorderPainted(false);
        btCuentasEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCuentasEmpleadosMouseClicked(evt);
            }
        });

        lbListaEmpleados.setText("Lista Empleados");

        lbCuentasEmpleados.setText("Cuentas");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbListaEmpleados)
                    .addComponent(btListaEmpleados))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btCuentasEmpleados))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lbCuentasEmpleados)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCuentasEmpleados)
                    .addComponent(btListaEmpleados))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbListaEmpleados)
                    .addComponent(lbCuentasEmpleados))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", jPanel7);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        lbNombreUsu.setText("Nombre Completo");

        lbPApellidoUsu.setText("Primer Apellido");

        lbSApellidoUsu.setText("Segundo Apellido");

        lbTipoIdenUsu.setText("Tipo Identificacion");

        lbNumIdenUsu.setText("Numero de Identificacion");

        lbTelUsu.setText("Telefono");

        lbDirUsu.setText("Direccion");

        LbTipoUsu.setText("Tipo de Usuario");

        campoPApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPApellidoActionPerformed(evt);
            }
        });

        comboTipoIdent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cedula de Ciudadania", "Cedula de Extranjeria", "Tarjeta de Identidad", "Registro Civil" }));

        combotipoUsu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paciente", "Empleado" }));

        btAgregarUsu.setText("Siguiente");
        btAgregarUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarUsuMouseClicked(evt);
            }
        });
        btAgregarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarUsuActionPerformed(evt);
            }
        });

        jLabel2.setText("Nuevo Usuario");

        registrarTelefono.setText("registrar teléfono");
        registrarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(298, 298, 298))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAgregarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbTipoUsu)
                            .addComponent(lbSApellidoUsu)
                            .addComponent(lbPApellidoUsu)
                            .addComponent(lbTipoIdenUsu)
                            .addComponent(lbDirUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNumIdenUsu)
                            .addComponent(lbTelUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoSApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(campoPApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(campoNomUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(combotipoUsu, 0, 301, Short.MAX_VALUE)
                            .addComponent(comboTipoIdent, 0, 301, Short.MAX_VALUE)
                            .addComponent(campoNumIdenUsu)
                            .addComponent(campoDirUsu)
                            .addComponent(registrarTelefono))))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campoPApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbPApellidoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSApellidoUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbTipoIdenUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNumIdenUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDirUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LbTipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboTipoIdent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNumIdenUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDirUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combotipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTelUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarTelefono))
                .addGap(22, 22, 22)
                .addComponent(btAgregarUsu)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Administracion de usuarios", jPanel2);

        btCerrarSesion.setBackground(new java.awt.Color(254, 254, 254));
        btCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/black-logout-256.png"))); // NOI18N
        btCerrarSesion.setText("Cerrar sesión");
        btCerrarSesion.setToolTipText("Cerrar sesión");
        btCerrarSesion.setBorder(null);
        btCerrarSesion.setBorderPainted(false);
        btCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCerrarSesion.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btCerrarSesion.setFocusPainted(false);
        btCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCerrarSesionMouseClicked(evt);
            }
        });
        btCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarSesionActionPerformed(evt);
            }
        });

        lbBienvenido.setText("Bienvenido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPApellidoActionPerformed

    private void btCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarSesionMouseClicked
       
        ventLog.setVisible(true);
        ventLog.getJpfcontraseña().setText("");
        ventLog.getJtfUsuario().setText("");
        dispose();
    }//GEN-LAST:event_btCerrarSesionMouseClicked

    private void btAgregarUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarUsuMouseClicked
        
        if(combotipoUsu.getSelectedItem() == "Paciente"){
        
            VentanaRegPaciente ventRegPaciente = new VentanaRegPaciente();
            ventRegPaciente.setVisible(true);
            ventRegPaciente.setLocationRelativeTo(null);
            ventRegPaciente.acomodarVentana(this);
            
            dispose();
            
            
        }else if(combotipoUsu.getSelectedItem() == "Empleado"){
        
            VentanaRegistroEmpleado ventRegEmp = new VentanaRegistroEmpleado();
            ventRegEmp.setVisible(true);
            ventRegEmp.setLocationRelativeTo(null);
            ventRegEmp.acomodarVentana(this);
            
            dispose();
        
        }
        
    }//GEN-LAST:event_btAgregarUsuMouseClicked


    private void btCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCerrarSesionActionPerformed

    private void btListaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btListaEmpleadosMouseClicked
       
        VentanaListadoEmpleados ventList = new VentanaListadoEmpleados();
        ventList.setVisible(true);
        ventList.setLocationRelativeTo(null);
        ventList.acomodarVentana(this);
        
        dispose();
    }//GEN-LAST:event_btListaEmpleadosMouseClicked

    private void btCuentasEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCuentasEmpleadosMouseClicked
       
        ventanaCuentas ventCuen = new ventanaCuentas();
        ventCuen.setVisible(true);
        ventCuen.setLocationRelativeTo(null);
        ventCuen.acomodarVentana(this);
        
        dispose();
        
        
    }//GEN-LAST:event_btCuentasEmpleadosMouseClicked

    private void btAgregarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarAreaActionPerformed
        
        registrarArea();
        
    }//GEN-LAST:event_btAgregarAreaActionPerformed

    private void registrarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarTelefonoActionPerformed
        
        VentanaRegistrarTelefono registrarNumeros = new VentanaRegistrarTelefono(telefonos);
        registrarNumeros.setVisible(true);
        registrarNumeros.setVentanaAdministrador(this);
        registrarNumeros.setAlwaysOnTop(true);
        registrarNumeros.setLocationRelativeTo(null);
        
        setEnabled(false);
        
    }//GEN-LAST:event_registrarTelefonoActionPerformed

    private void btAgregarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarUsuActionPerformed
        
        String nombre = campoNomUsu.getText();
        String apellido1 = campoPApellido.getText();
        String apellido2 = campoSApellido.getText();
        String tipoId = comboTipoIdent.getSelectedItem().toString();
        String numeroId = campoNumIdenUsu.getText();
        String direccion = campoDirUsu.getText();
        String tipoUsuario = combotipoUsu.getSelectedItem().toString();
        
        try {
        
            String [] datosValidar = {nombre, apellido1, numeroId, direccion};
            
            validar.validarModulos(datosValidar);
            
            String [] datosPersonales = {nombre, apellido1, apellido2, tipoId, numeroId, direccion, tipoUsuario};
            
            switch (tipoUsuario) {
                
                case "Paciente": {
                    
                    VentanaRegPaciente registrarPaciente = new VentanaRegPaciente();
                    registrarPaciente.acomodarVentana(this);
                    registrarPaciente.setDatosPersonales(datosPersonales, telefonos);
                    
                    setVisible(false);
                    
                }; break;
                    
                case "Empleado": {
                    
                    VentanaRegistroEmpleado registrarEmpleado = new VentanaRegistroEmpleado();
                    registrarEmpleado.acomodarVentana(this);
                    registrarEmpleado.setDatosPersonales(datosPersonales, telefonos);
                                        
                    setVisible(false);
                    
                }; break;
            }
            
        } catch (ExcepcionCamposVacios ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Campos requeridos sin llenar", JOptionPane.ERROR_MESSAGE);
            
        }
        
        
        
    }//GEN-LAST:event_btAgregarUsuActionPerformed

    
    public void limpiarCampos () {
        
        campoNomUsu.setText("");
        campoSApellido.setText("");
        campoPApellido.setText("");
        campoNumIdenUsu.setText("");
        campoDirUsu.setText("");
        comboTipoIdent.setSelectedIndex(0);
        combotipoUsu.setSelectedIndex(0);
        
    }
    

    public void acomodarVentana(VentanaLogin ventLog){
    
    this.ventLog = ventLog;
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaDescripCama;
    private javax.swing.JTextArea AreaDescripMedicamento;
    private javax.swing.JLabel LbTipoUsu;
    private javax.swing.JTextArea areaDescripArea;
    private javax.swing.JButton btAgregarArea;
    private javax.swing.JButton btAgregarCama;
    private javax.swing.JButton btAgregarMedicamento;
    private javax.swing.JButton btAgregarUsu;
    private javax.swing.JButton btCerrarSesion;
    private javax.swing.JButton btCuentasEmpleados;
    private javax.swing.JButton btListaEmpleados;
    private javax.swing.JTextField campoCodigoArea;
    private javax.swing.JTextField campoCodigoMedicamento;
    private javax.swing.JTextField campoCostoMedicamento;
    private javax.swing.JTextField campoDirUsu;
    private javax.swing.JTextField campoNomMedicamento;
    private javax.swing.JTextField campoNomUsu;
    private javax.swing.JTextField campoNombreArea;
    private javax.swing.JTextField campoNumIdenUsu;
    private javax.swing.JTextField campoNumeroCama;
    private javax.swing.JTextField campoPApellido;
    private javax.swing.JTextField campoSApellido;
    private javax.swing.JComboBox comboAreasCama;
    private javax.swing.JComboBox comboEstadocama;
    private javax.swing.JComboBox comboTipoIdent;
    private javax.swing.JComboBox combotipoUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbBienvenido;
    private javax.swing.JLabel lbCodAreaCama;
    private javax.swing.JLabel lbCodigoArea;
    private javax.swing.JLabel lbCodigoMedicamento;
    private javax.swing.JLabel lbCostoMedicamento;
    private javax.swing.JLabel lbCuentasEmpleados;
    private javax.swing.JLabel lbDescripArea;
    private javax.swing.JLabel lbDescripCama;
    private javax.swing.JLabel lbDescripMedicamento;
    private javax.swing.JLabel lbDirUsu;
    private javax.swing.JLabel lbEstadoCama;
    private javax.swing.JLabel lbListaEmpleados;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNombreArea;
    private javax.swing.JLabel lbNombreMedicamento;
    private javax.swing.JLabel lbNombreUsu;
    private javax.swing.JLabel lbNumCama;
    private javax.swing.JLabel lbNumIdenUsu;
    private javax.swing.JLabel lbPApellidoUsu;
    private javax.swing.JLabel lbSApellidoUsu;
    private javax.swing.JLabel lbSubTituloArea;
    private javax.swing.JLabel lbTelUsu;
    private javax.swing.JLabel lbTipoIdenUsu;
    private javax.swing.JLabel lbUser;
    private javax.swing.JButton registrarTelefono;
    // End of variables declaration//GEN-END:variables
}
