/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.DriverEnfermera;
import excepciones.ExcepcionCamposVacios;
import excepciones.Validador;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Telefono;

/**
 *
 * @author juliancv
 */
public class VentanaRegEnfermera extends javax.swing.JFrame {

    
    private VentanaRegistroEmpleado ventRegEmple;
    private VentanaAdministrador administrador;
    private ArrayList<Telefono> telefonos;
    private String [] datosPersonales;
    private Object[] datosEmpleado;
    private DefaultTableModel modelo;
    private Validador validar = new Validador();
    /**
     * Creates new form VentaRegEnfermera
     */
    public VentanaRegEnfermera() {
        initComponents();
        
        informacionHabilidad.setModel(modelo = new DefaultTableModel (new Object [][] {

            },
            new String [] {
                "Habilidad"
            })
         {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    
    public void establecerDatosEmpleado (ArrayList<Telefono> numeros, String [] datosPersonales, Object[] datosEmpleado) {
        
        telefonos = numeros;
        this.datosEmpleado = datosEmpleado;
        this.datosPersonales = datosPersonales;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void acomodarVentana(VentanaRegistroEmpleado ventRegEmple, VentanaAdministrador admin){
    
        this.ventRegEmple = ventRegEmple;
        administrador = admin;
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoAñosExp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        agregarHabilidad = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoHabilidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        informacionHabilidad = new javax.swing.JTable();
        eliminarHabilidad = new javax.swing.JButton();
        guardarEnfermera = new javax.swing.JButton();
        regresarEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setText("Registro Enfermera");

        jLabel2.setText("Años Experiencia");

        jLabel3.setText("Habilidades");

        agregarHabilidad.setText("Agregar");
        agregarHabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarHabilidadActionPerformed(evt);
            }
        });

        jLabel4.setText("Habilidad");

        informacionHabilidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Habilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(informacionHabilidad);
        if (informacionHabilidad.getColumnModel().getColumnCount() > 0) {
            informacionHabilidad.getColumnModel().getColumn(0).setResizable(false);
        }

        eliminarHabilidad.setText("Eliminar Habilidad");

        guardarEnfermera.setText("Guardar");
        guardarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEnfermeraActionPerformed(evt);
            }
        });

        regresarEmpleado.setText("Cancelar");
        regresarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarEmpleadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(regresarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(guardarEnfermera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(eliminarHabilidad))
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(campoHabilidad)
                                        .addGap(18, 18, 18)
                                        .addComponent(agregarHabilidad))
                                    .addComponent(campoAñosExp))))))
                .addGap(314, 314, 314))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoAñosExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoHabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarHabilidad))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarHabilidad))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarEnfermera)
                    .addComponent(regresarEmpleado))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarEmpleadoMouseClicked
        
        ventRegEmple.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_regresarEmpleadoMouseClicked

    private void guardarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarEnfermeraActionPerformed
    
        
        ArrayList<String>datos = new ArrayList<>();
        
        for (int i = 0; i < informacionHabilidad.getRowCount(); i++) {
            
            datos.add(informacionHabilidad.getValueAt(i, 0).toString());
            
        }
        
        try {
            
            int años = Integer.parseInt(campoAñosExp.getText());            
            datosPersonales[6] = "Enfermera";
            
            DriverEnfermera guardarDatos = new DriverEnfermera();
            
            guardarDatos.registrarEnfermera(datosPersonales[4], datosPersonales[3], datosPersonales[0], datosPersonales[1], 
                    datosPersonales[2], telefonos, datosPersonales[5], true, datosPersonales[6],datosEmpleado[0].toString(),
                    Double.parseDouble(datosEmpleado[1].toString()), datosEmpleado[2].toString(), datosEmpleado[3].toString(),
                    datosEmpleado[4].toString(), años, datos);
            
            JOptionPane.showMessageDialog(this, "Empleado registrado exitosamente", "Registro exitoso", 
                    JOptionPane.INFORMATION_MESSAGE);
        
            ventRegEmple.dispose();
            administrador.limpiarCampos();
            administrador.setVisible(true);

            dispose();
            
        } catch (NumberFormatException ex) {
            
            JOptionPane.showMessageDialog(this, "El campo de experiencia debe ser número en años", "Campos requeridos", 
                    JOptionPane.ERROR_MESSAGE);
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Registro fallido", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_guardarEnfermeraActionPerformed

    private void agregarHabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarHabilidadActionPerformed

        String habilidad = campoHabilidad.getText();
        
        try {
            
            validar.validarCampo(habilidad);
            
            boolean registrar = true;
            
            for (int i = 0; i < informacionHabilidad.getRowCount() && registrar == true; i++) {
                                                
                if (informacionHabilidad.getValueAt(i, 0).toString().equals(habilidad)) registrar = false;
                
            }
            
            if (registrar) {
                
                modelo.addRow(new String[] {habilidad});
                
                campoHabilidad.setText("");
                
            } else {
                
                JOptionPane.showMessageDialog(this, "La habilidad ya está registrada", "Valor duplicado", 
                        JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (ExcepcionCamposVacios ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Campos requeridos", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_agregarHabilidadActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarHabilidad;
    private javax.swing.JTextField campoAñosExp;
    private javax.swing.JTextField campoHabilidad;
    private javax.swing.JButton eliminarHabilidad;
    private javax.swing.JButton guardarEnfermera;
    private javax.swing.JTable informacionHabilidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresarEmpleado;
    // End of variables declaration//GEN-END:variables
}
